resources:
  - name:       MyIncomingArtifactoryWebhookResource
    type:       IncomingWebhook
    configuration:
      webhookName: ArtifactoryWebhook
 
pipelines:
  - name: Pipeline_Artifactory_Webhook
    steps:
    - name: receiveHook
      type: Bash
      configuration:
        inputResources:
          - name: MyIncomingArtifactoryWebhookResource
      execution:
          onExecute:
            - echo "$res_MyIncomingArtifactoryWebhookResource_payload" | jq '.' > payload.json
            - read_json payload.json "imageTag"
            - read_json payload.json "imageName"
            - echo "$debug"
